on: push

name: Workflow name test - nope
jobs:

  build:
    name: Build name test ${{ github.sha }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: step name test ${{ github.sha }}
