on: push

name: Workflow name test - nope
jobs:
  build:
    name: Build name test ${{ (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && "on default") || "not on default" }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: step name test ${{ (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && "on default") || "not on default" }}

