on: push

# Nothing dynamic seems to be allowed here
name: Workflow name test
env:
  ON_DEFAULT: ${{ (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && 'on default') || 'not on default' }}
jobs:
  build:
    # But this works
    name: Build name test ${{ env.ON_DEFAULT }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      # and this
      name: step name test ${{ env.ON_DEFAULT }}

